#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

begin
  hook_ref = payload[:boxfile][:config][:hook_ref]
rescue
  hook_ref = "stable"
end

local_md5 = execute "local md5" do
  command "cat /opt/nanobox/redis-#{hook_ref}.md5"
  not_if { ! ::File.exists? "/opt/nanobox/redis-#{hook_ref}.md5" }
end

aws_md5 = execute "aws md5" do
  command "curl -f -k https://s3.amazonaws.com/tools.nanobox.io/hooks/redis-#{hook_ref}.md5"
end

if local_md5 != aws_md5
  execute "update hooks" do
    command <<-END
bash -c 'curl \
    -f \
    -k \
    https://s3.amazonaws.com/tools.nanobox.io/hooks/redis-#{hook_ref}.tgz \
      | tar -xz -C /opt/nanobox/hooks && \
  curl \
    -f \
    -k \
    -o /opt/nanobox/redis-#{hook_ref}.md5 \
    https://s3.amazonaws.com/tools.nanobox.io/hooks/redis-#{hook_ref}.md5'
END
  end
end
